### PR TITLE
fix: avoid conflicting code actions on save

### LINKED ISSUE #143: WebStorm plugin 1.6.0: Code formatting aborted due to parsing errors + import statements not organized correctly on save
Hello,

On WebStorm 2024.3.4 (Build #WS-243.25659.40), I am facing the following notification with the WebStorm plugin 1.6.0:
> Biome: Code formatting aborted due to parsing errors. To format code with errors, enable the 'formatter.formatWithErrors' option.

Here are the plugin settings in my project:

Biome’s WebStorm plugin settings

Here is the Biome configuration file used by my project (Biome’s version is 1.9.4):
```json
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "files": {
    "ignore": [".gitignore", "package.json", "node_modules/**"],
    "ignoreUnknown": true
  },
  "vcs": {
    "enabled": true,
    "clientKind": "git",
    "useIgnoreFile": true,
    "defaultBranch": "main"
  },
  "formatter": {
    "indentStyle": "space",
    "lineWidth": 100
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "correctness": {
        "noUnusedImports": "error",
        "noUnusedVariables": "error"
      }
    }
  },
  "javascript": {
    "formatter": {
      "arrowParentheses": "asNeeded",
      "trailingCommas": "none"
    }
  },
  "json": {
    "parser": {
      "allowComments": false,
      "allowTrailingCommas": false
    }
  }
}
```

In addition, the following imports are not organized correctly on save:
```ts
import type { Context } from "../cli/cli.types.js";

import { inspect } from "node:util";
import { spawnSync } from "node:child_process";

import { setLogger } from "../logger/index.js";
```

The order of the two imports from Node.js modules remain the same, instead of being reversed like this:
```ts
import { spawnSync } from "node:child_process";
import { inspect } from "node:util";
```

I restarted Biome’s server, but it did not fix the issue.

I have verified that the version 1.5.6 of the plugin works correctly.

### PR DESCRIPTION
**Pull request by siketyan**
Closes #143 

Previously, safe fix + sort imports is executed in the following order:

1. Fetch safe fixes from the LSP server
2. Fetch sort imports from the LSP server
3. Apply the safe fixes
4. Apply the sort imports

At the second step, the LSP server assumes the safe fixes are not yet applied and returns text edits. However, we apply the safe fix in the third step. Thus, the edit in the forth step breaks the document.

I combined the first and second steps to one step, so the text edits provided by the LSP server won't be conflicted.

### CODE REVIEW

File: src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt [hunk 1]
```diff
@@ -68,49 +68,32 @@ class BiomeServerService(private val project: Project) {
...
-                        triggerKind = CodeActionTriggerKind.Automatic
-                    })
-
-                val codeActionResults = server.sendRequest { it.textDocumentService.codeAction(codeActionParams) }
-                codeActionResults?.forEach {
-                    if (it.isRight) {
-                        result.add(LspIntentionAction(server, it.right))
-                    }
-                }
+                actions.add("source.organizeImports.biome")
```
Comment (denbezrukov) [inline src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt:77]: Do you know if there could be a potential problem with the following case:
	1.	A quick fix returns text edits for imports.
	2.	Sorting imports changes the order.
	3.	The quick fix produces incorrect text edits (or sorting imports without the quick fix).

Comment (denbezrukov) [reply src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt:77]: Hm,
I recall that the some versions of LSP server do not return edits for sorting and quick fixes simultaneously. 
Probably we need to apply sorting and after that request quickfixes (or viceversa)?

Comment (siketyan) [reply src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt:77]: Even if the LSP server returns import sorting and quick fixes simultaneously, it's okay if the text edits are in a correct order. I tested some cases with quick fixes + sort imports in this branch, it's working perfectly for me. If you have a case that breaks a quick fix or import sorting, I'll revert that part to run the two actions separately.

Comment (siketyan) [reply src/main/kotlin/com/github/biomejs/intellijbiome/services/BiomeServerService.kt]: I reverted a part of the changes to just run the two actions separately.
